name = "Project"
version = "0.1.0"
defaultTargets = ["Project"]

[leanOptions]
warningAsError = true
pp.unicode.fun = true
autoImplicit = false
relaxedAutoImplicit = false
linter.mathlibStandardSet = true
linter.style.longLine = false

[[lean_lib]]
name = "Project"

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.27.0-rc1"
